spring:
  datasource:
    username: zyx
    password: Zyx3527109
    url: jdbc:mysql://localhost:3306/qualityevaluation?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  mail:
    host: smtp.qq.com
    username: 921197494@qq.com
    password: qfbyauxfpwtlbbgg
    properties:
      map: { "mail.smtp.ssl.enable=true": "true" }

  redis:
    host: 127.0.0.1
    port: 6379
    password: Zyx3527109
    timeout: 30000
    jedis:
      pool:
        max-active: 10

mybatis-plus:
  mapper-locations: classpath*:/mapper/**
  global-config:
    banner: false
#  configuration:
#    call-setters-on-nulls: false

server:
  port: 8080


